-- MySQL Script generated by MySQL Workbench
-- Tue Sep 20 17:28:23 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema hellobank
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hellobank
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hellobank` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`endereco` ;

CREATE TABLE IF NOT EXISTS `mydb`.`endereco` (
  `idendereco` INT NOT NULL,
  `rua` VARCHAR(45) NULL,
  PRIMARY KEY (`idendereco`))
ENGINE = InnoDB;

#idendereco n tem valor default?
#insert into `mydb`.`endereco` (rua) values ("Rua São João");

-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `idcliente` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `clientecol` VARCHAR(45) NULL,
  `idendereco` INT NULL,
  `endereco_idendereco` INT NULL,
  `clientecol1` VARCHAR(45) NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;

USE `hellobank` ;

-- -----------------------------------------------------
-- Table `hellobank`.`conta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hellobank`.`conta` ;

CREATE TABLE IF NOT EXISTS `hellobank`.`conta` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `data_criacao` DATETIME(6) NULL DEFAULT NULL,
  `saldo` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

select * from `hellobank`.`conta`;

insert into `hellobank`.`conta` (id, data_criacao, saldo) values (null, '2012-06-18 10:34:09', 3500.00);
insert into `hellobank`.`conta` (id, data_criacao, saldo) values (null, '2018-01-08 17:44:59', 700.88);
insert into `hellobank`.`conta` (id, data_criacao, saldo) values (null, '2016-06-30 15:13:05', 4522.10);
insert into `hellobank`.`conta` (id, data_criacao, saldo) values (null, '2020-04-11 09:52:18', 3500.00);
insert into `hellobank`.`conta` (id, data_criacao, saldo) values (null, '2010-12-01 20:03:48', 3500.00);

-- -----------------------------------------------------
-- Table `hellobank`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hellobank`.`cliente` ;

CREATE TABLE IF NOT EXISTS `hellobank`.`cliente` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `conta_id` BIGINT NULL DEFAULT NULL,
  `cpf` VARCHAR(255) NULL DEFAULT NULL,
  `data_criacao` DATETIME(6) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `rg` VARCHAR(255) NULL DEFAULT NULL,
  `telefone` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_r1u8010d60num5vc8fp0q1j2a` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `UK_cmxo70m08n43599l3h0h07cc6` (`email` ASC) VISIBLE,
  UNIQUE INDEX `UK_a0reg3hoo4hfq3o8mkoascfsm` (`rg` ASC) VISIBLE,
  UNIQUE INDEX `UK_cjamibneobl928lfs71yos48r` (`telefone` ASC) VISIBLE,
  CONSTRAINT `conta_id`
    FOREIGN KEY (`conta_id`)
    REFERENCES `hellobank`.`conta` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

select * from `hellobank`.`cliente`;

insert into `hellobank`.`cliente` (id,conta_id, cpf, data_criacao, email, nome, rg, telefone)
values (null, 26, "375.029.278-75","2021-06-18 11:34:33", "lucasaraujo@gmail.com","Lucas Araujo Gomes","12.962.994-7","(11) 84840-8957");

insert into `hellobank`.`cliente` (id,conta_id, cpf, data_criacao, email, nome, rg, telefone)
values (null, 30, "327.717.230-93","2021-01-04 21:03:39", "kyaracardz@hotmail.com","Kyara Cardozo","14.378.399-3","(21) 97731-0648");

insert into `hellobank`.`cliente` (id,conta_id, cpf, data_criacao, email, nome, rg, telefone)
values (null, 27, "355.254.300-70","2013-09-02 10:53:59", "ricardosantos@yahoo.com","Ricardo Santos","32.699.402-6","(84) 94693-2946");

insert into `hellobank`.`cliente` (id,conta_id, cpf, data_criacao, email, nome, rg, telefone)
values (null, 29, "835.911.570-23","1993-11-30 16:23:43", "maryjane@outlook.com","Maryjane Ifunanya","46.601.133-7","(62) 98527-9773");

insert into `hellobank`.`cliente` (id,conta_id, cpf, data_criacao, email, nome, rg, telefone)
values (null, 28, "119.450.000-58","1999-12-01 06:00:00", "cassiaroberta@gmail.com","Cassia Roberta","34.280.637-3","(88) 98933-2867");

-- -----------------------------------------------------
-- Table `hellobank`.`deposito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hellobank`.`deposito` ;

CREATE TABLE IF NOT EXISTS `hellobank`.`deposito` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `data` DATETIME(6) NULL DEFAULT NULL,
  `id_conta` BIGINT NULL DEFAULT NULL,
  `valor` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id_conta_1`
    FOREIGN KEY (`id_conta`)
    REFERENCES `hellobank`.`conta` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

select * from `hellobank`.`deposito`;

insert into `hellobank`.`deposito` (id, `data`, id_conta, valor) values (null, "2022-09-20 12:30:30", 26, 300.00);
insert into `hellobank`.`deposito` (id, `data`, id_conta, valor) values (null, "2021-10-02 13:40:37", 30, 100.00);
insert into `hellobank`.`deposito` (id, `data`, id_conta, valor) values (null, "2014-08-13 08:12:37", 30, 50.00);
insert into `hellobank`.`deposito` (id, `data`, id_conta, valor) values (null, "2018-01-25 16:16:16", 28, 1000.00);
insert into `hellobank`.`deposito` (id, `data`, id_conta, valor) values (null, "2019-01-01 12:07:01", 27, 75.00);

-- -----------------------------------------------------
-- Table `hellobank`.`endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hellobank`.`endereco` ;

CREATE TABLE IF NOT EXISTS `hellobank`.`endereco` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `bairro` VARCHAR(45) NULL DEFAULT NULL,
  `cep` VARCHAR(10) NULL DEFAULT NULL,
  `cidade` VARCHAR(45) NULL DEFAULT NULL,
  `logradouro` VARCHAR(45) NULL DEFAULT NULL,
  `numero` VARCHAR(5) NULL DEFAULT NULL,
  `uf` VARCHAR(2) NULL DEFAULT NULL,
  `cliente_idcliente` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id_endereco`),
  CONSTRAINT `FKrh0exj1329hbaqhhj8ikgcg2x`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `hellobank`.`cliente` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

select * from `hellobank`.`endereco`;

insert into `hellobank`.`endereco` (id_endereco, bairro, cep, cidade, logradouro, numero, uf, cliente_idcliente)
values (null, "Vila Maresia", "0135156","Ilha bela", "Rua dos laranjais", "322", 30);

insert into `hellobank`.`endereco` (id_endereco, bairro, cep, cidade, logradouro, numero, uf, cliente_idcliente)
values (null, "Vila Mariana", "09934123","São Paulo", "Rua Felipe Melo", "45A", 27);

insert into `hellobank`.`endereco` (id_endereco, bairro, cep, cidade, logradouro, numero, uf, cliente_idcliente)
values (null, "Centro", "24420880","Niterói", "Avenida do Bom Senhor", "880", 29);

insert into `hellobank`.`endereco` (id_endereco, bairro, cep, cidade, logradouro, numero, uf, cliente_idcliente)
values (null, "Jardim das nações", "33011020","Diadema", "Rua México", "144", 26);

insert into `hellobank`.`endereco` (id_endereco, bairro, cep, cidade, logradouro, numero, uf, cliente_idcliente)
values (null, "Jardim da Paz", "09910580","Rio Branco", "Avenida Tiradentes", "81", 28);



-- -----------------------------------------------------
-- Table `hellobank`.`saque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hellobank`.`saque` ;

CREATE TABLE IF NOT EXISTS `hellobank`.`saque` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `conta_id` BIGINT NULL DEFAULT NULL,
  `data` DATETIME(6) NULL DEFAULT NULL,
  `valor` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `conta_id_2`
    FOREIGN KEY (`conta_id`)
    REFERENCES `hellobank`.`conta` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

select * from `hellobank`.`saque`;
insert into `hellobank`.`saque` (id, conta_id, `data`,valor) values (null, 28, "2021-01-21 13:20:30", 300);
insert into `hellobank`.`saque` (id, conta_id, `data`,valor) values (null, 26, "1992-05-08 22:35:02", 1450.32);
insert into `hellobank`.`saque` (id, conta_id, `data`,valor) values (null, 27, "2022-10-04 17:33:12", 50.00);

-- -----------------------------------------------------
-- Table `hellobank`.`transferencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hellobank`.`transferencia` ;

CREATE TABLE IF NOT EXISTS `hellobank`.`transferencia` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `conta_id_recebe` BIGINT NULL DEFAULT NULL,
  `conta_id_saida` BIGINT NULL DEFAULT NULL,
  `data` DATETIME(6) NULL DEFAULT NULL,
  `valor` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `conta_id_recebe`
    FOREIGN KEY (`conta_id_recebe`)
    REFERENCES `hellobank`.`conta` (`id`),
  CONSTRAINT `conta_id_saida`
    FOREIGN KEY (`conta_id_saida`)
    REFERENCES `hellobank`.`conta` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

select * from `hellobank`.`transferencia`;
insert into `hellobank`.`transferencia` (id, conta_id_recebe, conta_id_saida, `data`, valor) values (null, 28, 30, "2002-02-02 02:22:22", 340.00);
insert into `hellobank`.`transferencia` (id, conta_id_recebe, conta_id_saida, `data`, valor) values (null, 27, 29, "1990-06-09 09:06:34", 30.00);
insert into `hellobank`.`transferencia` (id, conta_id_recebe, conta_id_saida, `data`, valor) values (null, 26, 27, "2022-04-08 08:08:16", 500.00);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
