-- MySQL Script generated by MySQL Workbench
-- Tue Sep 20 17:28:23 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema hellobank
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hellobank
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hellobank` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`endereco` ;

CREATE TABLE IF NOT EXISTS `mydb`.`endereco` (
  `idendereco` INT NOT NULL,
  `rua` VARCHAR(45) NULL,
  PRIMARY KEY (`idendereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `idcliente` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `clientecol` VARCHAR(45) NULL,
  `idendereco` INT NULL,
  `endereco_idendereco` INT NULL,
  `clientecol1` VARCHAR(45) NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;

USE `hellobank` ;

-- -----------------------------------------------------
-- Table `hellobank`.`conta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hellobank`.`conta` ;

CREATE TABLE IF NOT EXISTS `hellobank`.`conta` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `data_criacao` DATETIME(6) NULL DEFAULT NULL,
  `saldo` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hellobank`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hellobank`.`cliente` ;

CREATE TABLE IF NOT EXISTS `hellobank`.`cliente` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `conta_id` BIGINT NULL DEFAULT NULL,
  `cpf` VARCHAR(255) NULL DEFAULT NULL,
  `data_criacao` DATETIME(6) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `rg` VARCHAR(255) NULL DEFAULT NULL,
  `telefone` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_r1u8010d60num5vc8fp0q1j2a` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `UK_cmxo70m08n43599l3h0h07cc6` (`email` ASC) VISIBLE,
  UNIQUE INDEX `UK_a0reg3hoo4hfq3o8mkoascfsm` (`rg` ASC) VISIBLE,
  UNIQUE INDEX `UK_cjamibneobl928lfs71yos48r` (`telefone` ASC) VISIBLE,
  CONSTRAINT `conta_id`
    FOREIGN KEY (`conta_id`)
    REFERENCES `hellobank`.`conta` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hellobank`.`deposito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hellobank`.`deposito` ;

CREATE TABLE IF NOT EXISTS `hellobank`.`deposito` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `data` DATETIME(6) NULL DEFAULT NULL,
  `id_conta` BIGINT NULL DEFAULT NULL,
  `valor` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id_conta_1`
    FOREIGN KEY (`id_conta`)
    REFERENCES `hellobank`.`conta` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hellobank`.`endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hellobank`.`endereco` ;

CREATE TABLE IF NOT EXISTS `hellobank`.`endereco` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `bairro` VARCHAR(45) NULL DEFAULT NULL,
  `cep` VARCHAR(10) NULL DEFAULT NULL,
  `cidade` VARCHAR(45) NULL DEFAULT NULL,
  `logradouro` VARCHAR(45) NULL DEFAULT NULL,
  `numero` VARCHAR(5) NULL DEFAULT NULL,
  `uf` VARCHAR(2) NULL DEFAULT NULL,
  `cliente_idcliente` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id_endereco`),
  CONSTRAINT `FKrh0exj1329hbaqhhj8ikgcg2x`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `hellobank`.`cliente` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hellobank`.`saque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hellobank`.`saque` ;

CREATE TABLE IF NOT EXISTS `hellobank`.`saque` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `conta_id` BIGINT NULL DEFAULT NULL,
  `data` DATETIME(6) NULL DEFAULT NULL,
  `valor` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `conta_id_2`
    FOREIGN KEY (`conta_id`)
    REFERENCES `hellobank`.`conta` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hellobank`.`transferencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hellobank`.`transferencia` ;

CREATE TABLE IF NOT EXISTS `hellobank`.`transferencia` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `conta_id_recebe` BIGINT NULL DEFAULT NULL,
  `conta_id_saida` BIGINT NULL DEFAULT NULL,
  `data` DATETIME(6) NULL DEFAULT NULL,
  `valor` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `conta_id_recebe`
    FOREIGN KEY (`conta_id_recebe`)
    REFERENCES `hellobank`.`conta` (`id`),
  CONSTRAINT `conta_id_saida`
    FOREIGN KEY (`conta_id_saida`)
    REFERENCES `hellobank`.`conta` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
